--[[
    BloxHub GUI Framework v2.0
    Author: BloxHub (Generated by an AI based on PRD)
    Last Update: 2025-11-12

    Description:
    A universal, single-file, component-based GUI framework for Roblox.
    It provides fully customizable and composable UI building blocks,
    not a static template. Designed for power and flexibility.
]]

-- Environment setup for cross-executor compatibility
local getgenv = getgenv or function() return _G end
local writefile = writefile or function(...) print("FileSystem is not supported in this environment.") end
local readfile = readfile or function(...) print("FileSystem is not supported in this environment.") end
local isfile = isfile or function(...) return false end

-- Roblox Services
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local HttpService = game:GetService("HttpService")
local CoreGui = game:GetService("CoreGui")

-- Main Library Table
local BloxHub = {
    Core = {},
    UI = {},
    Elements = {},
    Settings = {},
    State = {},
    Utilities = {}
}

--//===========================================================================//
--// [UTILITIES] - Helper functions used throughout the library
--//===========================================================================//

BloxHub.Utilities.CreateInstance = function(className, properties)
    local instance = Instance.new(className)
    for prop, value in pairs(properties or {}) do
        pcall(function() instance[prop] = value end)
    end
    return instance
end

BloxHub.Utilities.Tween = function(instance, properties, duration, easingStyle, easingDirection)
    duration = duration or 0.2
    easingStyle = easingStyle or Enum.EasingStyle.Quad
    easingDirection = easingDirection or Enum.EasingDirection.Out
    local tweenInfo = TweenInfo.new(duration, easingStyle, easingDirection)
    local tween = TweenService:Create(instance, tweenInfo, properties)
    tween:Play()
    return tween
end

BloxHub.Utilities.GetTextBounds = function(text, font, size, parent)
    local textLabel = Instance.new("TextLabel")
    textLabel.Font = font
    textLabel.Text = text
    textLabel.TextSize = size
    textLabel.Parent = parent or CoreGui
    local bounds = textLabel.TextBounds
    textLabel:Destroy()
    return bounds
end

--//===========================================================================//
--// [SETTINGS & THEME] - Default configurations and theme management
--//===========================================================================//

BloxHub.Settings.DefaultTheme = {
    Background = Color3.fromHex("#0F0F0F"),
    Accent = Color3.fromHex("#0078FF"),
    Highlight = Color3.fromHex("#00A2FF"),
    Text = Color3.fromHex("#FFFFFF"),
    TextSecondary = Color3.fromHex("#A0A0A0"),
    Error = Color3.fromHex("#FF4C4C"),
    Success = Color3.fromHex("#4CAF50"),
    Border = Color3.fromHex("#212121"),

    Font = Enum.Font.SourceSans,
    TextSize = 14,
    TitleSize = 16,

    CornerRadius = 10,
    SmallCornerRadius = 6,
}

BloxHub.Settings.CurrentTheme = BloxHub.Settings.DefaultTheme

BloxHub.Settings.DefaultConfig = {
    WindowPosition = UDim2.new(0.5, -250, 0.5, -200),
    Hotkeys = {},
    Toggles = {},
    Sliders = {},
}

BloxHub.State.Config = BloxHub.Settings.DefaultConfig
BloxHub.State.Visible = true
BloxHub.State.ListeningForKeybind = nil
BloxHub.State.ActivePopups = {}

--//===========================================================================//
--// [CORE SYSTEMS] - Input, Persistence, and Main GUI management
--//===========================================================================//

local MainScreenGui = BloxHub.Utilities.CreateInstance("ScreenGui", {
    Name = "BloxHubFramework_Gui",
    Parent = CoreGui,
    ZIndexBehavior = Enum.ZIndexBehavior.Global,
    ResetOnSpawn = false
})

BloxHub.Core.InputHandler = function()
    UserInputService.InputBegan:Connect(function(input, gameProcessedEvent)
        if gameProcessedEvent and input.UserInputType ~= Enum.UserInputType.MouseButton1 and input.UserInputType ~= Enum.UserInputType.MouseButton2 then
            return
        end

        if BloxHub.State.ListeningForKeybind then
            local keybindComponent = BloxHub.State.ListeningForKeybind
            local key
            if input.UserInputType == Enum.UserInputType.MouseButton1 then
                key = "Mouse1"
            elseif input.UserInputType == Enum.UserInputType.MouseButton2 then
                key = "Mouse2"
            else
                key = input.KeyCode.Name
            end
            
            local modifiers = {}
            if UserInputService:IsKeyDown(Enum.KeyCode.LeftControl) or UserInputService:IsKeyDown(Enum.KeyCode.RightControl) then table.insert(modifiers, "Ctrl") end
            if UserInputService:IsKeyDown(Enum.KeyCode.LeftAlt) or UserInputService:IsKeyDown(Enum.KeyCode.RightAlt) then table.insert(modifiers, "Alt") end
            if UserInputService:IsKeyDown(Enum.KeyCode.LeftShift) or UserInputService:IsKeyDown(Enum.KeyCode.RightShift) then table.insert(modifiers, "Shift") end

            local keyString = table.concat(modifiers, "+") .. (next(modifiers) and "+" or "") .. key
            keybindComponent:SetKey(keyString)
            BloxHub.State.ListeningForKeybind = nil
            return
        end
        
        -- Handle global hotkeys here if needed
    end)
end

BloxHub.Core.SaveConfig = function()
    local configData = HttpService:JSONEncode(BloxHub.State.Config)
    writefile("BloxHub_Config.json", configData)
    getgenv().BloxHubSettings = configData -- Fallback
end

BloxHub.Core.LoadConfig = function()
    local success, data
    if isfile("BloxHub_Config.json") then
        success, data = pcall(function() return HttpService:JSONDecode(readfile("BloxHub_Config.json")) end)
    elseif getgenv().BloxHubSettings then
        success, data = pcall(function() return HttpService:JSONDecode(getgenv().BloxHubSettings) end)
    end
    
    if success and type(data) == "table" then
        for key, value in pairs(data) do
            BloxHub.State.Config[key] = value
        end
    end
end

BloxHub.Core.ToggleGUI = function()
    BloxHub.State.Visible = not BloxHub.State.Visible
    for _, child in ipairs(MainScreenGui:GetChildren()) do
        if child:IsA("Frame") then -- Assuming top-level elements are frames
            child.Visible = BloxHub.State.Visible
        end
    end
end

--//===========================================================================//
--// [UI COMPONENTS] - The building blocks of the framework
--//===========================================================================//

local BaseComponent = {}
BaseComponent.__index = BaseComponent

function BaseComponent.new(className, properties)
    local self = setmetatable({}, BaseComponent)
    self.Instance = BloxHub.Utilities.CreateInstance(className, properties)
    self.ClassName = className
    self.Events = {}
    return self
end

function BaseComponent:On(event, callback)
    if not self.Events[event] then
        self.Events[event] = {}
    end
    table.insert(self.Events[event], callback)
end

function BaseComponent:Fire(event, ...)
    if self.Events[event] then
        for _, callback in ipairs(self.Events[event]) do
            task.spawn(callback, ...)
        end
    end
end

function BaseComponent:Destroy()
    self.Instance:Destroy()
    for k in pairs(self) do
        self[k] = nil
    end
end

--- Window Component
local Window = setmetatable({}, BaseComponent)
Window.__index = Window

function BloxHub.UI.CreateWindow(title, options)
    options = options or {}
    local self = setmetatable(BaseComponent.new("Frame", {
        Name = "Window",
        Size = options.Size or UDim2.new(0, 500, 0, 400),
        Position = BloxHub.State.Config.WindowPosition,
        BackgroundColor3 = BloxHub.Settings.CurrentTheme.Background,
        BorderSizePixel = 0,
        ClipsDescendants = true,
        Parent = MainScreenGui
    }), Window)

    self.Instance:SetAttribute("Component", self)

    local corner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0, BloxHub.Settings.CurrentTheme.CornerRadius), Parent = self.Instance })
    local stroke = BloxHub.Utilities.CreateInstance("UIStroke", { Color = BloxHub.Settings.CurrentTheme.Border, Thickness = 1, Parent = self.Instance })

    -- Title Bar
    local titleBar = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "TitleBar",
        Size = UDim2.new(1, 0, 0, 30),
        BackgroundColor3 = BloxHub.Settings.CurrentTheme.Accent,
        BorderSizePixel = 0,
        Parent = self.Instance
    })
    local titleCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0, BloxHub.Settings.CurrentTheme.CornerRadius), Parent = titleBar })
    titleCorner.Parent = nil; titleCorner.Parent = titleBar -- Bug fix for corners

    local titleLabel = BloxHub.Utilities.CreateInstance("TextLabel", {
        Name = "TitleLabel",
        Size = UDim2.new(1, -10, 1, 0),
        Position = UDim2.new(0, 5, 0, 0),
        BackgroundColor3 = Color3.new(1, 1, 1),
        BackgroundTransparency = 1,
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = title,
        TextColor3 = BloxHub.Settings.CurrentTheme.Text,
        TextSize = BloxHub.Settings.CurrentTheme.TitleSize,
        TextXAlignment = Enum.TextXAlignment.Left,
        Parent = titleBar
    })

    -- Content Area
    local contentArea = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "ContentArea",
        Size = UDim2.new(1, 0, 1, -30),
        Position = UDim2.new(0, 0, 0, 30),
        BackgroundTransparency = 1,
        Parent = self.Instance
    })
    
    self.Tabs = {}
    self.TabButtons = {}
    self.ActiveTab = nil

    local tabContainer = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "TabContainer",
        Size = UDim2.new(0, 120, 1, 0),
        BackgroundColor3 = BloxHub.Settings.CurrentTheme.Background,
        BorderSizePixel = 0,
        Parent = contentArea
    })
    local listLayout = BloxHub.Utilities.CreateInstance("UIListLayout", {
        Padding = UDim.new(0, 5),
        SortOrder = Enum.SortOrder.LayoutOrder,
        Parent = tabContainer
    })

    self.ContentContainer = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "ContentContainer",
        Size = UDim2.new(1, -120, 1, 0),
        Position = UDim2.new(0, 120, 0, 0),
        BackgroundTransparency = 1,
        Parent = contentArea
    })
    
    -- Draggable Logic
    local dragging = false
    local dragStart
    local startPos

    titleBar.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            dragStart = input.Position
            startPos = self.Instance.Position
            
            local dragConn, stopConn
            dragConn = UserInputService.InputChanged:Connect(function(inputChanged)
                if inputChanged.UserInputType == Enum.UserInputType.MouseMovement then
                    local delta = inputChanged.Position - dragStart
                    self.Instance.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
                end
            end)
            stopConn = UserInputService.InputEnded:Connect(function(inputEnded)
                if inputEnded.UserInputType == Enum.UserInputType.MouseButton1 then
                    dragging = false
                    dragConn:Disconnect()
                    stopConn:Disconnect()
                    BloxHub.State.Config.WindowPosition = self.Instance.Position
                    BloxHub.Core.SaveConfig()
                end
            end)
        end
    end)
    
    return self
end

function Window:CreateTab(title)
    local tabContent = BloxHub.Utilities.CreateInstance("Frame", {
        Name = title,
        Size = UDim2.new(1, 0, 1, 0),
        BackgroundTransparency = 1,
        Visible = false,
        Parent = self.ContentContainer
    })

    local padding = BloxHub.Utilities.CreateInstance("UIPadding", {
        PaddingLeft = UDim.new(0, 10),
        PaddingRight = UDim.new(0, 10),
        PaddingTop = UDim.new(0, 10),
        PaddingBottom = UDim.new(0, 10),
        Parent = tabContent
    })

    local listLayout = BloxHub.Utilities.CreateInstance("UIListLayout", {
        Padding = UDim.new(0, 5),
        SortOrder = Enum.SortOrder.LayoutOrder,
        Parent = tabContent
    })

    local tab = {
        Title = title,
        Container = tabContent,
        Elements = {},
        Layout = listLayout
    }
    
    local tabButton = BloxHub.Utilities.CreateInstance("TextButton", {
        Name = title .. "_Button",
        Size = UDim2.new(1, 0, 0, 35),
        BackgroundColor3 = BloxHub.Settings.CurrentTheme.Background,
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = title,
        TextColor3 = BloxHub.Settings.CurrentTheme.TextSecondary,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        Parent = self.Instance.ContentArea.TabContainer
    })

    tab.Button = tabButton
    self.Tabs[title] = tab
    table.insert(self.TabButtons, tabButton)

    local function setActiveTab()
        if self.ActiveTab then
            self.ActiveTab.Container.Visible = false
            BloxHub.Utilities.Tween(self.ActiveTab.Button, {
                TextColor3 = BloxHub.Settings.CurrentTheme.TextSecondary,
                BackgroundColor3 = BloxHub.Settings.CurrentTheme.Background
            })
        end
        
        self.ActiveTab = tab
        tab.Container.Visible = true
        BloxHub.Utilities.Tween(tabButton, {
            TextColor3 = BloxHub.Settings.CurrentTheme.Text,
            BackgroundColor3 = BloxHub.Settings.CurrentTheme.Highlight
        })
    end

    tabButton.MouseButton1Click:Connect(setActiveTab)
    
    if not self.ActiveTab then
        setActiveTab()
    end
    
    -- Attach API methods to the tab table
    local tabAPI = {}
    
    function tabAPI:AddButton(text, callback)
        local button = BloxHub.UI.CreateButton(text, callback)
        button.Instance.Parent = tab.Container
        table.insert(tab.Elements, button)
        return button
    end
    
    function tabAPI:AddToggle(text, default, callback)
        local toggle = BloxHub.UI.CreateToggle(text, default, callback)
        toggle.Instance.Parent = tab.Container
        table.insert(tab.Elements, toggle)
        return toggle
    end
    
    function tabAPI:AddSlider(text, min, max, default, callback)
        local slider = BloxHub.UI.CreateSlider(text, min, max, default, callback)
        slider.Instance.Parent = tab.Container
        table.insert(tab.Elements, slider)
        return slider
    end
    
    function tabAPI:AddKeybind(text, defaultKey, callback)
        local keybind = BloxHub.UI.CreateKeybind(text, defaultKey, callback)
        keybind.Instance.Parent = tab.Container
        table.insert(tab.Elements, keybind)
        return keybind
    end
    
    function tabAPI:AddDropdown(text, options, callback)
        local dropdown = BloxHub.UI.CreateDropdown(text, options, callback)
        dropdown.Instance.Parent = tab.Container
        table.insert(tab.Elements, dropdown)
        return dropdown
    end

    function tabAPI:AddLabel(text)
        local label = BloxHub.UI.CreateLabel(text)
        label.Instance.Parent = tab.Container
        table.insert(tab.Elements, label)
        return label
    end

    return tabAPI
end

--- Button Component
function BloxHub.UI.CreateButton(text, callback)
    local self = BaseComponent.new("TextButton", {
        Name = "Button",
        Size = UDim2.new(1, 0, 0, 30),
        BackgroundColor3 = BloxHub.Settings.CurrentTheme.Accent,
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = text,
        TextColor3 = BloxHub.Settings.CurrentTheme.Text,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
    })

    local corner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0, BloxHub.Settings.CurrentTheme.SmallCornerRadius), Parent = self.Instance })

    self.Instance.MouseEnter:Connect(function()
        BloxHub.Utilities.Tween(self.Instance, { BackgroundColor3 = BloxHub.Settings.CurrentTheme.Highlight })
    end)
    self.Instance.MouseLeave:Connect(function()
        BloxHub.Utilities.Tween(self.Instance, { BackgroundColor3 = BloxHub.Settings.CurrentTheme.Accent })
    end)
    self.Instance.MouseButton1Click:Connect(function()
        pcall(callback)
        self:Fire("Click")
    end)
    
    return self
end

--- Toggle Component
function BloxHub.UI.CreateToggle(text, default, callback)
    local self = BaseComponent.new("Frame", {
        Name = "Toggle",
        Size = UDim2.new(1, 0, 0, 30),
        BackgroundTransparency = 1,
    })

    self.State = default or false

    local label = BloxHub.Utilities.CreateInstance("TextLabel", {
        Name = "Label",
        Size = UDim2.new(1, -45, 1, 0),
        Position = UDim2.new(0, 0, 0, 0),
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = text,
        TextColor3 = BloxHub.Settings.CurrentTheme.Text,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        TextXAlignment = Enum.TextXAlignment.Left,
        BackgroundTransparency = 1,
        Parent = self.Instance
    })
    
    local switch = BloxHub.Utilities.CreateInstance("TextButton", {
        Name = "Switch",
        Size = UDim2.new(0, 40, 0, 20),
        Position = UDim2.new(1, -40, 0.5, -10),
        BackgroundColor3 = self.State and BloxHub.Settings.CurrentTheme.Accent or Color3.fromHex("#333"),
        Text = "",
        Parent = self.Instance
    })
    local switchCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0.5, 0), Parent = switch })
    
    local nub = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "Nub",
        Size = UDim2.new(0, 16, 0, 16),
        Position = self.State and UDim2.new(1, -18, 0.5, -8) or UDim2.new(0, 2, 0.5, -8),
        BackgroundColor3 = Color3.new(1, 1, 1),
        BorderSizePixel = 0,
        Parent = switch
    })
    local nubCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0.5, 0), Parent = nub })

    function self:SetState(newState)
        self.State = newState
        local nubPos = self.State and UDim2.new(1, -18, 0.5, -8) or UDim2.new(0, 2, 0.5, -8)
        local switchColor = self.State and BloxHub.Settings.CurrentTheme.Accent or Color3.fromHex("#333")
        BloxHub.Utilities.Tween(nub, { Position = nubPos })
        BloxHub.Utilities.Tween(switch, { BackgroundColor3 = switchColor })
        
        pcall(callback, self.State)
        self:Fire("StateChanged", self.State)
    end
    
    switch.MouseButton1Click:Connect(function()
        self:SetState(not self.State)
    end)
    
    return self
end

--- Slider Component
function BloxHub.UI.CreateSlider(text, min, max, default, callback)
    local self = BaseComponent.new("Frame", {
        Name = "Slider",
        Size = UDim2.new(1, 0, 0, 40),
        BackgroundTransparency = 1
    })

    self.Min, self.Max, self.Value = min, max, default

    local label = BloxHub.Utilities.CreateInstance("TextLabel", {
        Name = "Label",
        Size = UDim2.new(0.5, 0, 0, 20),
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = text,
        TextColor3 = BloxHub.Settings.CurrentTheme.Text,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        TextXAlignment = Enum.TextXAlignment.Left,
        BackgroundTransparency = 1,
        Parent = self.Instance
    })
    
    local valueLabel = BloxHub.Utilities.CreateInstance("TextLabel", {
        Name = "ValueLabel",
        Size = UDim2.new(0.5, 0, 0, 20),
        Position = UDim2.new(0.5, 0, 0, 0),
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = tostring(default),
        TextColor3 = BloxHub.Settings.CurrentTheme.TextSecondary,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        TextXAlignment = Enum.TextXAlignment.Right,
        BackgroundTransparency = 1,
        Parent = self.Instance
    })
    
    local track = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "Track",
        Size = UDim2.new(1, 0, 0, 6),
        Position = UDim2.new(0, 0, 0, 25),
        BackgroundColor3 = Color3.fromHex("#333"),
        Parent = self.Instance
    })
    local trackCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0.5, 0), Parent = track })
    
    local progress = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "Progress",
        Size = UDim2.new((default-min)/(max-min), 0, 1, 0),
        BackgroundColor3 = BloxHub.Settings.CurrentTheme.Accent,
        Parent = track
    })
    local progressCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0.5, 0), Parent = progress })
    
    local dragging = false
    function self:SetValue(newValue)
        local clampedValue = math.clamp(newValue, self.Min, self.Max)
        self.Value = clampedValue
        valueLabel.Text = string.format("%.2f", clampedValue)
        
        local percentage = (clampedValue - self.Min) / (self.Max - self.Min)
        BloxHub.Utilities.Tween(progress, { Size = UDim2.new(percentage, 0, 1, 0) })
        
        pcall(callback, self.Value)
        self:Fire("ValueChanged", self.Value)
    end

    track.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            local mouseX = UserInputService:GetMouseLocation().X
            local trackAbsPos = track.AbsolutePosition.X
            local trackAbsSize = track.AbsoluteSize.X
            local percentage = math.clamp((mouseX - trackAbsPos) / trackAbsSize, 0, 1)
            local newValue = self.Min + (self.Max - self.Min) * percentage
            self:SetValue(newValue)
            
            local moveConn, endConn
            moveConn = UserInputService.InputChanged:Connect(function(inputChanged)
                if inputChanged.UserInputType == Enum.UserInputType.MouseMovement then
                    local newMouseX = inputChanged.Position.X
                    local newPercentage = math.clamp((newMouseX - trackAbsPos) / trackAbsSize, 0, 1)
                    local newSliderValue = self.Min + (self.Max - self.Min) * newPercentage
                    self:SetValue(newSliderValue)
                end
            end)
            endConn = UserInputService.InputEnded:Connect(function(inputEnded)
                if inputEnded.UserInputType == Enum.UserInputType.MouseButton1 then
                    dragging = false
                    moveConn:Disconnect()
                    endConn:Disconnect()
                end
            end)
        end
    end)
    
    return self
end

--- Keybind Component
function BloxHub.UI.CreateKeybind(text, defaultKey, callback)
    local self = BaseComponent.new("Frame", {
        Name = "Keybind",
        Size = UDim2.new(1, 0, 0, 30),
        BackgroundTransparency = 1
    })

    self.Key = defaultKey or "None"
    
    local label = BloxHub.Utilities.CreateInstance("TextLabel", {
        Name = "Label",
        Size = UDim2.new(1, -105, 1, 0),
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = text,
        TextColor3 = BloxHub.Settings.CurrentTheme.Text,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        TextXAlignment = Enum.TextXAlignment.Left,
        BackgroundTransparency = 1,
        Parent = self.Instance
    })
    
    local keyButton = BloxHub.Utilities.CreateInstance("TextButton", {
        Name = "KeyButton",
        Size = UDim2.new(0, 100, 1, 0),
        Position = UDim2.new(1, -100, 0, 0),
        BackgroundColor3 = Color3.fromHex("#333"),
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = "["..self.Key.."]",
        TextColor3 = BloxHub.Settings.CurrentTheme.Text,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        Parent = self.Instance
    })
    local keyCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0, BloxHub.Settings.CurrentTheme.SmallCornerRadius), Parent = keyButton })

    function self:SetKey(newKey)
        self.Key = newKey
        keyButton.Text = "["..self.Key.."]"
        BloxHub.State.ListeningForKeybind = nil
        BloxHub.Utilities.Tween(keyButton, { BackgroundColor3 = Color3.fromHex("#333") })
        
        pcall(callback, self.Key)
        self:Fire("KeyChanged", self.Key)
    end
    
    keyButton.MouseButton1Click:Connect(function()
        if BloxHub.State.ListeningForKeybind == self then
            BloxHub.State.ListeningForKeybind = nil
            keyButton.Text = "["..self.Key.."]"
            BloxHub.Utilities.Tween(keyButton, { BackgroundColor3 = Color3.fromHex("#333") })
        else
            if BloxHub.State.ListeningForKeybind then -- Cancel previous one
                BloxHub.State.ListeningForKeybind:SetKey(BloxHub.State.ListeningForKeybind.Key)
            end
            BloxHub.State.ListeningForKeybind = self
            keyButton.Text = "[...]"
            BloxHub.Utilities.Tween(keyButton, { BackgroundColor3 = BloxHub.Settings.CurrentTheme.Accent })
        end
    end)
    
    return self
end

--- Dropdown Component
function BloxHub.UI.CreateDropdown(text, options, callback)
    local self = BaseComponent.new("Frame", {
        Name = "Dropdown",
        Size = UDim2.new(1, 0, 0, 30),
        BackgroundTransparency = 1,
        ClipsDescendants = false,
        ZIndex = 2
    })

    self.Options = options
    self.Selected = options[1]
    self.IsOpen = false
    
    local mainButton = BloxHub.Utilities.CreateInstance("TextButton", {
        Name = "MainButton",
        Size = UDim2.new(1, 0, 1, 0),
        BackgroundColor3 = Color3.fromHex("#333"),
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = text .. ": " .. self.Selected,
        TextColor3 = BloxHub.Settings.CurrentTheme.Text,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        Parent = self.Instance
    })
    local mainCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0, BloxHub.Settings.CurrentTheme.SmallCornerRadius), Parent = mainButton })
    
    local dropdownFrame = BloxHub.Utilities.CreateInstance("Frame", {
        Name = "DropdownFrame",
        Size = UDim2.new(1, 0, 0, #options * 30),
        Position = UDim2.new(0, 0, 1, 5),
        BackgroundColor3 = Color3.fromHex("#222"),
        Visible = false,
        ClipsDescendants = true,
        ZIndex = 3,
        Parent = self.Instance
    })
    local dropCorner = BloxHub.Utilities.CreateInstance("UICorner", { CornerRadius = UDim.new(0, BloxHub.Settings.CurrentTheme.SmallCornerRadius), Parent = dropdownFrame })
    local dropLayout = BloxHub.Utilities.CreateInstance("UIListLayout", { SortOrder = Enum.SortOrder.LayoutOrder, Parent = dropdownFrame })

    local function toggleDropdown()
        self.IsOpen = not self.IsOpen
        dropdownFrame.Visible = self.IsOpen
    end

    mainButton.MouseButton1Click:Connect(toggleDropdown)

    for i, optionText in ipairs(options) do
        local optionButton = BloxHub.Utilities.CreateInstance("TextButton", {
            Name = optionText,
            Size = UDim2.new(1, 0, 0, 30),
            BackgroundColor3 = Color3.fromHex("#222"),
            Font = BloxHub.Settings.CurrentTheme.Font,
            Text = optionText,
            TextColor3 = BloxHub.Settings.CurrentTheme.Text,
            TextSize = BloxHub.Settings.CurrentTheme.TextSize,
            LayoutOrder = i,
            Parent = dropdownFrame
        })
        
        optionButton.MouseEnter:Connect(function() optionButton.BackgroundColor3 = Color3.fromHex("#444") end)
        optionButton.MouseLeave:Connect(function() optionButton.BackgroundColor3 = Color3.fromHex("#222") end)
        
        optionButton.MouseButton1Click:Connect(function()
            self.Selected = optionText
            mainButton.Text = text .. ": " .. self.Selected
            pcall(callback, self.Selected)
            self:Fire("SelectionChanged", self.Selected)
            toggleDropdown()
        end)
    end
    
    return self
end

--- Label Component
function BloxHub.UI.CreateLabel(text)
    local self = BaseComponent.new("TextLabel", {
        Name = "Label",
        Size = UDim2.new(1, 0, 0, 20),
        BackgroundTransparency = 1,
        Font = BloxHub.Settings.CurrentTheme.Font,
        Text = text,
        TextColor3 = BloxHub.Settings.CurrentTheme.TextSecondary,
        TextSize = BloxHub.Settings.CurrentTheme.TextSize,
        TextXAlignment = Enum.TextXAlignment.Left,
    })
    return self
end

--//===========================================================================//
--// [PUBLIC API] - The developer-facing functions to build the GUI
--//===========================================================================//

function BloxHub.Elements.CreateWindow(title, options)
    return BloxHub.UI.CreateWindow(title, options)
end

--//===========================================================================//
--// [INITIALIZATION] - Load config, start systems, and create example GUI
--//===========================================================================//

return function()
    BloxHub.Core.LoadConfig()
    BloxHub.Core.InputHandler()
    
    -- Create the default example GUI as described in the PRD
    local Main = BloxHub.Elements.CreateWindow("BloxHub Framework v2.0")

    -- Main Features Tab
    local FeaturesTab = Main:CreateTab("Features")
    
    FeaturesTab:AddToggle("Enable ESP", false, function(state)
        print("ESP State:", state)
    end)
    
    FeaturesTab:AddToggle("Chams", true, function(state)
        print("Chams State:", state)
    end)
    
    FeaturesTab:AddSlider("FOV", 30, 120, 90, function(value)
        print("FOV set to:", value)
    end)

    FeaturesTab:AddKeybind("Aimbot Key", "E", function(key)
        print("Aimbot key changed to:", key)
    end)

    -- Misc Tab
    local MiscTab = Main:CreateTab("Misc")
    
    MiscTab:AddButton("Spawn Dummy", function()
        print("Dummy Spawned!")
    end)
    
    MiscTab:AddDropdown("WalkSpeed", {"16 (Default)", "32", "64", "100"}, function(choice)
        print("Selected WalkSpeed:", choice)
        local speed = tonumber(choice:match("%d+"))
        if game.Players.LocalPlayer and game.Players.LocalPlayer.Character and game.Players.LocalPlayer.Character:FindFirstChild("Humanoid") then
            game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = speed
        end
    end)

    -- Settings Tab
    local SettingsTab = Main:CreateTab("Settings")
    SettingsTab:AddLabel("UI Settings")
    SettingsTab:AddKeybind("Toggle GUI Key", "RightControl", function(key)
        print("Toggle key set to:", key, "(Functionality not implemented in this example)")
    end)
    SettingsTab:AddButton("Save Configuration", function()
        BloxHub.Core.SaveConfig()
        print("Configuration Saved!")
    end)

    print("BloxHub GUI Framework Initialized.")
    
    -- Return the public API
    return BloxHub.Elements
end
